dist: xenial

language: node_js
node_js: node

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn format:validate
  - yarn lint
  - yarn test
  - yarn test:coverage:lcov | npx coveralls
  - yarn test:coverage:lcov | npx codacy-coverage
